// <auto-generated />
using System;
using JuegoBatallasMagicas.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuegoBatallasMagicas.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250609084127_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.AccionCombate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CombateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuracionAplicada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DanoInfligido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EscudoAplicado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HabilidadUsadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManaRestanteAtacante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManaRestanteObjetivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroTurno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonajeAtacanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonajeObjetivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaRestanteAtacante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaRestanteObjetivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CombateId");

                    b.HasIndex("HabilidadUsadaId");

                    b.HasIndex("PersonajeAtacanteId");

                    b.HasIndex("PersonajeObjetivoId");

                    b.ToTable("AccionesCombate");
                });

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.Combate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCombate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GanadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Personaje1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Personaje2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GanadorId");

                    b.HasIndex("Personaje1Id");

                    b.HasIndex("Personaje2Id");

                    b.ToTable("Combates");
                });

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CosteMana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoEfecto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorEfecto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fuerza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManaActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManaMaximo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaMaxima")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.PersonajeHabilidad", b =>
                {
                    b.Property<int>("PersonajeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HabilidadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonajeId", "HabilidadId");

                    b.HasIndex("HabilidadId");

                    b.ToTable("PersonajeHabilidades");
                });

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.AccionCombate", b =>
                {
                    b.HasOne("JuegoBatallasMagicas.API.Models.Combate", "Combate")
                        .WithMany("Acciones")
                        .HasForeignKey("CombateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuegoBatallasMagicas.API.Models.Habilidad", "HabilidadUsada")
                        .WithMany()
                        .HasForeignKey("HabilidadUsadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JuegoBatallasMagicas.API.Models.Personaje", "PersonajeAtacante")
                        .WithMany()
                        .HasForeignKey("PersonajeAtacanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JuegoBatallasMagicas.API.Models.Personaje", "PersonajeObjetivo")
                        .WithMany()
                        .HasForeignKey("PersonajeObjetivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combate");

                    b.Navigation("HabilidadUsada");

                    b.Navigation("PersonajeAtacante");

                    b.Navigation("PersonajeObjetivo");
                });

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.Combate", b =>
                {
                    b.HasOne("JuegoBatallasMagicas.API.Models.Personaje", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorId");

                    b.HasOne("JuegoBatallasMagicas.API.Models.Personaje", "Personaje1")
                        .WithMany()
                        .HasForeignKey("Personaje1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JuegoBatallasMagicas.API.Models.Personaje", "Personaje2")
                        .WithMany()
                        .HasForeignKey("Personaje2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ganador");

                    b.Navigation("Personaje1");

                    b.Navigation("Personaje2");
                });

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.PersonajeHabilidad", b =>
                {
                    b.HasOne("JuegoBatallasMagicas.API.Models.Habilidad", "Habilidad")
                        .WithMany("PersonajeHabilidades")
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuegoBatallasMagicas.API.Models.Personaje", "Personaje")
                        .WithMany("PersonajeHabilidades")
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.Combate", b =>
                {
                    b.Navigation("Acciones");
                });

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.Habilidad", b =>
                {
                    b.Navigation("PersonajeHabilidades");
                });

            modelBuilder.Entity("JuegoBatallasMagicas.API.Models.Personaje", b =>
                {
                    b.Navigation("PersonajeHabilidades");
                });
#pragma warning restore 612, 618
        }
    }
}
